[project]
name = "openllv-webui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gradio>=6.22.0",
    "openllv",
    "sqlalchemy>=2.0.51",
]

[tool.uv.sources]
openllv = { git = "https://github.com/glory-wan/openLLV.git" }
